# Generated by Django 6.1 on 2026-09-27 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_attribute_remove_product_price_product_base_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='display_order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
