# Generated by Django 6.1 on 2026-09-27 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0008_productvariant_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariant',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, unique=True),
        ),
    ]
