# Generated by Django 6.1 on 2026-09-27 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0009_alter_productvariant_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='variant',
        ),
        migrations.AddField(
            model_name='productimage',
            name='variant',
            field=models.ManyToManyField(null=True, related_name='images', to='API.productvariant'),
        ),
    ]
