# Generated by Django 6.1 on 2026-09-28 12:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0011_variantattributevalue_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variantattributevalue',
            name='attribute',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='API.attribute'),
        ),
    ]
