# Generated by Django 6.1 on 2026-09-28 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0012_alter_variantattributevalue_attribute'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='discount_price',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='discount_price',
        ),
    ]
