# Generated by Django 6.1 on 2026-09-28 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0013_remove_product_discount_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariant',
            name='slug',
        ),
    ]
