# Generated by Django 6.1 on 2026-09-08 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('price', models.FloatField()),
                ('discription', models.CharField(max_length=3000)),
                ('category', models.CharField(max_length=250)),
                ('image', models.CharField()),
            ],
        ),
    ]
