# Generated by Django 6.1 on 2026-09-09 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_cart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='user_id',
            new_name='username',
        ),
    ]
