# Generated by Django 6.1 on 2026-09-24 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_brand_slug_alter_category_slug_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='brand_id',
            new_name='brand',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='category_id',
            new_name='category',
        ),
    ]
